# Nombre_de_Usuario = input("ingrese su nombre: ")
# print("hola",Nombre_de_Usuario)
# num1 = int(input("ingrese un numero "))
# num2 = int(input("ingrese un numero "))
# print("la suma da = ",num1 + num2)
# nombre = input("ingrese su nombre ")
# apellido = input("ingrese su apellido ")
# edad = input("ingrese su edad ")
# print(nombre,apellido,edad)
# nombre2 = input("Ingrese su nombre: ")
# comision = input("Ingrese su comision: ")
# asignatura = input("Ingrese la asignatura: ")
# docente = input("Ingrese el nombre del docente: ")
# presente = input("¿Estuvo presente?: ")
# print("Nombre:" + nombre2)
# print("Comision:" + comision)
# print("Asignatura:" + asignatura)
# print("Docente:"+ docente)
# print("Presente:"+ presente)        
###lado = float(input("ingrese el lado del cuadrado: "))
# superficie = lado ** 2
#print("La superficie del cuadrado es:",superficie)
# lado1 = int(input("Ingrese un numero: "))
# lado2 = int(input("Ingrese un numero: "))
# superficie2 = lado1 * lado2 / 2
# print("La superficie del triangulo es:",superficie2)
# largo = int(input("ingrese el largo del rectangulo: "))
# ancho = int(input("ingrese el ancho del rectangulo: "))
# superficie3 = largo * ancho
# print("La superficie del rectangulo es:",superficie3)
###producto = input("Ingrese el nombre del producto: ")
# precio = int(input("Ingrese el precio del producto: "))
# iva = precio / 100 * 21
# print("El valor de los impuestos(IVA) es:",iva)
# nombre = input("ingrese su nombre ")
# apellido = input("ingrese su apellido ")
# nota1 = int(input("ingrese su nota: "))
# nota2 = int(input("ingrese su nota: "))
# nota3 = int(input("ingrese su nota: "))
# promedio = nota1 + nota2 + nota3
# print("Nota 1:",nota1)
# print("Nota 2:",nota2)
# print("Nota 3:",nota3)
# print("Promedio:",promedio/3)
nombre = input("ingrese su nombre: ")
edad = int(input("ingrese su edad: "))
print("Su edad en 10 años sera:",edad + 10)